import { randomUUID } from 'node:crypto';
import express, { type NextFunction, type Request, type Response } from 'express';
import multer from 'multer';
import { formSchema, type ErrorResponse, type GenerationRequest, type GenerationResponse } from './contracts.js';
import type { AuthService } from './auth.js';
import type { AuthStore } from './database.js';
import { ServiceError, invalid } from './errors.js';
import type { MemeGenerator } from './generator.js';

export type Dependencies = { auth: AuthService; store: AuthStore; generator: MemeGenerator; log?: (event: Record<string, unknown>) => void };
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 1 } }); const accepted = new Set(['image/jpeg', 'image/png']);
export function createApp(deps: Dependencies) {
  const app = express(); app.disable('x-powered-by'); app.use(express.json({ limit: '16kb' })); app.get('/health', (_req, res) => res.status(200).json({ ok: true }));
  app.post('/auth/register', wrap(async req => deps.auth.register(req.body))); app.post('/auth/login', wrap(async req => deps.auth.login(req.body))); app.post('/auth/refresh', wrap(async req => deps.auth.refresh(req.body)));
  function wrap(handler: (req: Request) => Promise<unknown>) { return async (req: Request, res: Response, next: NextFunction) => { try { res.status(200).json(await handler(req)); } catch (error) { next(error); } }; }
  app.post('/v1/meme-replies', upload.single('source'), async (req, res, next) => { const requestId = randomUUID(); const started = Date.now(); let principal: { userId: string; deviceId: string } | undefined; try { principal = await deps.auth.verifyBearer(req.header('authorization')); if (!req.file || !accepted.has(req.file.mimetype) || !hasMatchingSignature(req.file.buffer, req.file.mimetype)) throw invalid('即梦参考图仅支持 PNG 或 JPEG 图片。'); const parsed = formSchema.safeParse(req.body); if (!parsed.success) throw invalid('情绪或自定义回击语无效。'); const result = await deps.generator.generate({ source: { bytes: req.file.buffer, mimeType: req.file.mimetype as GenerationRequest['source']['mimeType'], filename: req.file.originalname || 'source.png' }, ...parsed.data }); const elapsedMs = Date.now() - started; await deps.store.logGeneration({ requestId, userId: principal.userId, deviceId: principal.deviceId, status: 'success', elapsedMs, model: deps.generator.model }); deps.log?.({ requestId, status: 200, elapsedMs }); const body: GenerationResponse = { requestId, ...result }; res.status(200).json(body); } catch (error) { if (principal) void deps.store.logGeneration({ requestId, userId: principal.userId, deviceId: principal.deviceId, status: 'failed', elapsedMs: Date.now() - started, model: deps.generator.model }).catch(() => undefined); next(withRequestId(error, requestId, started, deps)); } });
  app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { const wrapped = error as ServiceError & { requestId?: string }; const status = wrapped instanceof ServiceError ? wrapped.status : isMulterError(error) ? 400 : 502; const code = wrapped instanceof ServiceError ? wrapped.code : isMulterError(error) ? 'INVALID_REQUEST' : 'UPSTREAM_FAILURE'; const message = wrapped instanceof ServiceError ? wrapped.message : isMulterError(error) ? '图片超过大小限制或上传格式错误。' : '图像生成服务暂时不可用。'; const body: ErrorResponse = { requestId: wrapped.requestId || randomUUID(), code, message }; res.status(status).json(body); }); return app;
}
function withRequestId(error: unknown, requestId: string, started: number, deps: Dependencies) { const wrapped = error instanceof Error ? error : new Error('Unknown error'); (wrapped as Error & { requestId?: string }).requestId = requestId; deps.log?.({ requestId, status: error instanceof ServiceError ? error.status : isMulterError(error) ? 400 : 502, elapsedMs: Date.now() - started, category: error instanceof ServiceError ? error.code : isMulterError(error) ? 'INVALID_REQUEST' : 'UPSTREAM_FAILURE' }); return wrapped; }
function isMulterError(error: unknown): error is multer.MulterError { return error instanceof multer.MulterError; }
function hasMatchingSignature(bytes: Buffer, mimeType: string) { if (mimeType === 'image/png') return bytes.subarray(0, 8).equals(Buffer.from([137,80,78,71,13,10,26,10])); if (mimeType === 'image/jpeg') return bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff; return bytes.subarray(0, 4).toString('ascii') === 'RIFF' && bytes.subarray(8, 12).toString('ascii') === 'WEBP'; }
